version: '3.8'

services:
  gaplek:
    image: gaplek:v2.1.0
    container_name: gaplek
    ports:
      - 50051:50051
    environment:
      - APP_HOST=0.0.0.0
      - PORT=50051
    restart: unless-stopped
    tty: true